# Generated by Django 5.0.14 on 2026-01-19 18:22

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('reviewer', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('submission', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-review_text'],
                'indexes': [models.Index(fields=['-review_text'], name='game_review_review__f3c604_idx')],
            },
        ),
    ]
