# Generated by Django 5.0.14 on 2026-01-20 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereview',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='gamereview',
            name='game_review_review__f3c604_idx',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gamereview',
            index=models.Index(fields=['-created'], name='game_review_created_ec405f_idx'),
        ),
    ]
