# Generated by Django 5.2.12 on 2026-03-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0004_game_gamereview_like_count_profile_reviewlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamereview',
            name='like_count',
        ),
    ]
