# Generated by Django 5.2.12 on 2026-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0006_gamereview_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='like_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
